const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..');
const data=JSON.parse(fs.readFileSync(path.join(root,'docs/assessment-lab/data.json'),'utf8'));
let code=fs.readFileSync(path.join(root,'docs/assessment-lab/lab.js'),'utf8');
code=code.slice(0,code.indexOf("window.addEventListener('hashchange'"));
const ctx=vm.createContext({console,URL,setTimeout,clearTimeout});
vm.runInContext(code,ctx);vm.runInContext(`D=${JSON.stringify(data)}`,ctx);
function check(expr){assert.equal(vm.runInContext(expr,ctx),true,expr);}
check('D.cases.length===7 && D.session.assignments.length===7');
check('D.session.assignments.reduce((a,v)=>a+v.members,0)===27');
check('freshTeam(caseForTeam(7)).members.length===3');
check('freshTeam(caseForTeam(1)).members.length===4');
check("total(freshReview(caseForTeam(1))).startsWith('Pendiente')");
check("total({...freshReview(caseForTeam(1)),scores:['0','0','0','0']})==='Total: 0 / 100'");
check("total({...freshReview(caseForTeam(1)),scores:['25','15','25','0']})==='Total: 65 / 100'");
check("!validRecord({...freshReview(caseForTeam(1)),scores:['25','20','15','0']},'review',caseForTeam(1))");
check("!validRecord(freshTeam(caseForTeam(1)),'team',caseForTeam(2))");
check("!validRecord({...freshTeam(caseForTeam(1)),version:'999'},'team',caseForTeam(1))");
check("!validRecord({...freshTeam(caseForTeam(1)),members:[]},'team',caseForTeam(1))");
check("validLinkedIn('https://www.linkedin.com/in/ejemplo') && !validLinkedIn('javascript:alert(1)') && !validLinkedIn('https://linkedin.com.evil.test/in/test') && !validLinkedIn('https://www.linkedin.com/company/test')");
check("!esc('<img src=x onerror=alert(1)>').includes('<')");
check("!('evil' in sanitizeRecord({...freshReview(caseForTeam(1)),evil:'untrusted'},'review',caseForTeam(1)))");
vm.runInContext("teamData(1).together='Equipo uno';teamData(2).together='Equipo dos';",ctx);
check("teamData(1).together==='Equipo uno' && teamData(2).together==='Equipo dos'");
vm.runInContext("activeTeam=1;activeSlot=1;reviewData().name='Persona uno';activeSlot=2;reviewData().name='Persona dos';activeSlot=1",ctx);
check("reviewData().name==='Persona uno'");
check("teamErrors(freshTeam(caseForTeam(7))).length>0");
check("teamReport(caseForTeam(1),{...teamData(1),phrase:'<script>alert(1)</script>'}).includes('&lt;script&gt;')");
const source=fs.readFileSync(path.join(root,'content/assessment-lab/casos-ad26.md'),'utf8');
for(const c of data.cases)for(const s of [...c.context,c.task,c.pressure,c.audience])assert(source.includes(s),`Source drift: ${c.id}`);
assert.deepEqual(data.rubric,JSON.parse(fs.readFileSync(path.join(root,'content/assessment-lab/rubrica.json'),'utf8')));
assert.equal(data.centralQuestions.length,4);
vm.runInContext("var exported; download=(name,body,type)=>{exported={name,body,type}};notify=()=>{};exportReport('prueba',teamReport(caseForTeam(1),teamData(1)));",ctx);
check("exported.name==='prueba.html' && exported.type==='text/html;charset=utf-8' && exported.body.includes('<!doctype html>') && exported.body.includes('Equipo uno')");
vm.runInContext("var restored=JSON.parse(JSON.stringify({schema:1,kind:'team',session:D.session.id,team:1,record:teamData(1)}));",ctx);
check("validRecord(restored.record,'team',caseForTeam(1)) && sanitizeRecord(restored.record,'team',caseForTeam(1)).together==='Equipo uno'");
console.log('OK: assignment, case fidelity, rubric, pending vs zero, totals, isolation, backup validation, URL safety, HTML escaping and report generation.');
