const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..'), read=p=>fs.readFileSync(path.join(root,p),'utf8');
const data=JSON.parse(read('docs/assessment-lab/data.json'));
const source=read('docs/assessment-lab/lab.js'), html=read('docs/assessment-lab/index.html');
const ctx=vm.createContext({console,URL,setTimeout,clearTimeout});
vm.runInContext(source.slice(0,source.indexOf("window.addEventListener('hashchange'")),ctx);
vm.runInContext(`D=${JSON.stringify(data)}`,ctx);
const check=e=>assert.equal(vm.runInContext(e,ctx),true,e);
check('D.cases.length===7 && D.questions.length===4');
check('freshTeam(caseForTeam(7)).members.length===3 && freshTeam(caseForTeam(1)).members.length===4');
check("validLinkedIn('https://www.linkedin.com/in/ejemplo') && !validLinkedIn('javascript:alert(1)') && !validLinkedIn('https://linkedin.com.evil.test/in/test')");
check("validRecord(freshTeam(caseForTeam(1)),'team',caseForTeam(1)) && !validRecord(freshTeam(caseForTeam(1)),'team',caseForTeam(2))");
check("!('extra' in sanitizeRecord({...freshTeam(caseForTeam(1)),extra:'x'},'team',caseForTeam(1)))");
vm.runInContext("teamData(1).together='Equipo uno';teamData(2).together='Equipo dos';",ctx);
check("teamData(1).together==='Equipo uno' && teamData(2).together==='Equipo dos'");
check("teamReport(caseForTeam(1),{...teamData(1),phrase:'<script>alert(1)</script>'}).includes('&lt;script&gt;')");
check("teamView().includes('Ver propuesta') && evaluation().includes('Rúbrica de la UF')");
assert(!('centralQuestions' in data));
for(const forbidden of ['reviewView','bindReview','Método del Lab','Descargar respaldo','Importar respaldo','Cerrar propuesta','página 2','lámina digital'])assert(!(source+html+JSON.stringify(data)).includes(forbidden),forbidden);
for(const f of ['REGLAS_ASSESSMENT_LAB.md','ARQUITECTURA_Y_AUDITORIA.md'])assert(!fs.existsSync(path.join(root,'docs/assessment-lab',f)));
const cases=read('content/assessment-lab/casos-ad26.md');
for(const c of data.cases)for(const s of [...c.context,c.task,c.pressure,c.audience])assert(cases.includes(s));
assert.deepEqual(data.rubric,JSON.parse(read('content/assessment-lab/rubrica.json')));
console.log('OK: student navigation, case fidelity, rubric, form, proposal, validation, escaping and removal of educator tools.');
